name: CI

on:
  push:
    branches:
       - master
  schedule:
       # Once a week on saturday
       - cron: '7 13 * * 6' 
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "11.0"
          directory: ${{ runner.temp }}/llvm
      - name: Fetch dependencies
        run: |
          sudo apt update
          sudo apt install libx11-dev libxft-dev libbsd-dev -y
      - name: Build
        run: make CC=clang
      - uses: cachix/install-nix-action@v13
        if: github.event_name == 'push'
        with:
          nix_path: nixpkgs=channel:nixos-20.09
          extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"
      - name: Run coverage with Nix test-driver
        run: nix-build coverage/test.nix
      - name: Push coverage data to Codacy
        if: github.event_name == 'push'
        run: >
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report
          --commit-uuid ${{ github.sha }}
          --force-language C
          -r result/coverage_data/tabbed-alacritty.lcov

