name: CI

on:
  push:
    branches:
       - master
  schedule:
       # Once a week on saturday
       - cron: '7 13 * * 6' 
  workflow_dispatch:

env:
  NUR_REPO: shamilton
  CACHIX_CACHE: scott-hamilton
  NIXPKGS_ALLOW_BROKEN: 0
  CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v13
        if: github.event_name == 'push'
        with:
          nix_path: nixpkgs=channel:nixos-20.09
          extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"
      - name: Run coverage with Nix test-driver
        run: |
          nix-build coverage/test.nix
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: result/coverage_data
      - name: Push coverage data to Codacy
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: result/coverage_data/tabbed-alacritty.lcov
