name: CI

on:
  push:
    branches:
       - master
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v13
        if: github.event_name == 'push'
        with:
          nix_path: nixpkgs=channel:nixos-20.09
      - name: Run coverage with Nix test-driver
        run: nix-build coverage/test.nix --show-trace
      # - name: Push coverage data to Codacy
      #   if: github.event_name == 'push'
      #   run: >
      #     bash <(curl -Ls https://coverage.codacy.com/get.sh) report
      #     --commit-uuid ${{ github.sha }}
      #     --force-language C
      #     -r result/coverage_data/tabbed-alacritty.lcov

