name: CI

on:
  push:
    branches:
       - master
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v13
        if: github.event_name == 'push'
        with:
          nix_path: nixpkgs=channel:nixos-20.09
      - name: Run coverage with Nix test-driver
        run: >
          nix-build '<nixpkgs/nixos>' \
            --argstr system x86_64-linux \
            --arg configuration '{ virtualisation.qemu.pkgs = import <nixpkgs> { system = "x86_64-darwin"; }; }' \
            -A vm \
            -I nixpkgs=http://github.com/SCOTT-HAMILTON/NixPkgs/archive/230f823cd985e499ff2fd450b419bc5b44c6dbf8.tar.gz
        run: nix-build coverage/test.nix --show-trace
      # - name: Push coverage data to Codacy
      #   if: github.event_name == 'push'
      #   run: >
      #     bash <(curl -Ls https://coverage.codacy.com/get.sh) report
      #     --commit-uuid ${{ github.sha }}
      #     --force-language C
      #     -r result/coverage_data/tabbed-alacritty.lcov

